name: Express deploy

on:
  push:
    branches: [ master ]

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
    - name: Deploy app
      uses: appleboy/ssh-action@v0.1.2
      with:
        host: ${{secrets.SSH_HOST}}
        port: ${{secrets.SSH_PORT}}
        username: ${{secrets.SSH_USERNAME}}
        key: ${{secrets.SSH_PRIVATE_KEY}}
        script: |
          cd ~/satnik
          git reset origin/master --hard
          npm ci
          npm run build
          PORT=8080 npm run start
